import type { ComponentType, SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement> & {
  alt?: string;
  color?: string;
  mirrored?: boolean;
  size?: number | string;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
};

export type Icon = ComponentType<IconProps>;

export { Airplane } from "@phosphor-icons/react/dist/csr/Airplane";
export { AirplaneTakeoff } from "@phosphor-icons/react/dist/csr/AirplaneTakeoff";
export { ArrowRight } from "@phosphor-icons/react/dist/csr/ArrowRight";
export { ArrowSquareOut } from "@phosphor-icons/react/dist/csr/ArrowSquareOut";
export { Baby } from "@phosphor-icons/react/dist/csr/Baby";
export { Bed } from "@phosphor-icons/react/dist/csr/Bed";
export { Bell } from "@phosphor-icons/react/dist/csr/Bell";
export { BellRinging } from "@phosphor-icons/react/dist/csr/BellRinging";
export { Buildings } from "@phosphor-icons/react/dist/csr/Buildings";
export { CalendarBlank } from "@phosphor-icons/react/dist/csr/CalendarBlank";
export { CaretRight } from "@phosphor-icons/react/dist/csr/CaretRight";
export { ChatCircle } from "@phosphor-icons/react/dist/csr/ChatCircle";
export { CheckCircle } from "@phosphor-icons/react/dist/csr/CheckCircle";
export { ChefHat } from "@phosphor-icons/react/dist/csr/ChefHat";
export { Circle } from "@phosphor-icons/react/dist/csr/Circle";
export { CloudRain } from "@phosphor-icons/react/dist/csr/CloudRain";
export { CloudSun } from "@phosphor-icons/react/dist/csr/CloudSun";
export { Confetti } from "@phosphor-icons/react/dist/csr/Confetti";
export { CookingPot } from "@phosphor-icons/react/dist/csr/CookingPot";
export { DownloadSimple } from "@phosphor-icons/react/dist/csr/DownloadSimple";
export { FileText } from "@phosphor-icons/react/dist/csr/FileText";
export { ForkKnife } from "@phosphor-icons/react/dist/csr/ForkKnife";
export { GameController } from "@phosphor-icons/react/dist/csr/GameController";
export { Gear } from "@phosphor-icons/react/dist/csr/Gear";
export { Gift } from "@phosphor-icons/react/dist/csr/Gift";
export { Golf } from "@phosphor-icons/react/dist/csr/Golf";
export { Heart } from "@phosphor-icons/react/dist/csr/Heart";
export { HouseLine } from "@phosphor-icons/react/dist/csr/HouseLine";
export { MapPin } from "@phosphor-icons/react/dist/csr/MapPin";
export { MapTrifold } from "@phosphor-icons/react/dist/csr/MapTrifold";
export { Moon } from "@phosphor-icons/react/dist/csr/Moon";
export { Package } from "@phosphor-icons/react/dist/csr/Package";
export { PaperPlaneTilt } from "@phosphor-icons/react/dist/csr/PaperPlaneTilt";
export { PencilSimple } from "@phosphor-icons/react/dist/csr/PencilSimple";
export { PushPin } from "@phosphor-icons/react/dist/csr/PushPin";
export { Question } from "@phosphor-icons/react/dist/csr/Question";
export { ShieldCheck } from "@phosphor-icons/react/dist/csr/ShieldCheck";
export { ShoppingBag } from "@phosphor-icons/react/dist/csr/ShoppingBag";
export { ShoppingCart } from "@phosphor-icons/react/dist/csr/ShoppingCart";
export { Shuffle } from "@phosphor-icons/react/dist/csr/Shuffle";
export { SlidersHorizontal } from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
export { Sparkle } from "@phosphor-icons/react/dist/csr/Sparkle";
export { SquaresFour } from "@phosphor-icons/react/dist/csr/SquaresFour";
export { Star } from "@phosphor-icons/react/dist/csr/Star";
export { Suitcase } from "@phosphor-icons/react/dist/csr/Suitcase";
export { Sun } from "@phosphor-icons/react/dist/csr/Sun";
export { SwimmingPool } from "@phosphor-icons/react/dist/csr/SwimmingPool";
export { Trash } from "@phosphor-icons/react/dist/csr/Trash";
export { Tree } from "@phosphor-icons/react/dist/csr/Tree";
export { Umbrella } from "@phosphor-icons/react/dist/csr/Umbrella";
export { User } from "@phosphor-icons/react/dist/csr/User";
export { UserCircle } from "@phosphor-icons/react/dist/csr/UserCircle";
export { UsersThree } from "@phosphor-icons/react/dist/csr/UsersThree";
export { Wallet } from "@phosphor-icons/react/dist/csr/Wallet";
export { Waves } from "@phosphor-icons/react/dist/csr/Waves";
export { WhatsappLogo } from "@phosphor-icons/react/dist/csr/WhatsappLogo";
export { WifiHigh } from "@phosphor-icons/react/dist/csr/WifiHigh";
export { Wind } from "@phosphor-icons/react/dist/csr/Wind";
